version: "3.8"

name: jenkins

services:
  # Service 1: Docker Daemon (Docker-in-Docker)
  docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    command:
    - --storage-driver=overlay2
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
    ports:
      - "2376:2376"
    restart: unless-stopped

  # Service 2: Jenkins Controller
  jenkins:
    image: myjenkins-blueocean:2.541.1
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-blueocean
    restart: unless-stopped
    networks:
      - jenkins
    ports:
      - "8080:8080"   # Jenkins UI
      - "50000:50000" # Agent port
    environment:
      # Connects Jenkins to the Docker Daemon service
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro

# Create a bridge network for internal communication
networks:
  jenkins:
    name: jenkins

# Persist data so you don't lose configuration on restart
volumes:
  jenkins-data:
    name: jenkins-data
  jenkins-docker-certs:
    name: jenkins-docker-certs
